name: Tests

on:
  push:

jobs:
  tests:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            sanitize: On
            testexe: test
          - os: windows-latest
            sanitize: Off
            testexe: Debug/test.exe
          - os: macos-latest
            sanitize: On
            testexe: test
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - name: CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DWITH_SANITIZERS=${{matrix.sanitize}} ${{github.workspace}}/test
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug
      - name: Test
        run: ${{github.workspace}}/build/${{matrix.testexe}} --plain
